### ISSUE TITLE
Regression:  Observable TypeError: x3dom.reload is not a function

### ISSUE THREAD

**Issue by jamesleesaunders** [x3dom/x3dom#966]
I have been using Observable to create some X3DOM notebook example. Due to the reactive nature of Observable we have to use x3dom.reload() at times (another story I would like one day to find a better solution for). 

In have put together 2 simple examples to display this issue:

In 1.7.2 this works:
https://observablehq.com/@jamesleesaunders/simple-x3dom-example-v1-7-2 

In dev this does not work:
https://observablehq.com/@jamesleesaunders/simple-x3dom-example-dev

For some reason it thinks x3dom.reload() does not exist (when I know it does).
`reloader = TypeError: x3dom.reload is not a function`

I don't know if this is a regression as such, it may be an issue more-so with the way Observable loads modules. But I thought I had best point it out as this is something which used to work on v1.7.2 and now no longer works.

**Comment by jamesleesaunders** [comment]
Observable may be the only corner use case for this in which case I wouldn’t worry, but it may affect other uses?

**Comment by tsturm** [comment]
fixed

**Comment by jamesleesaunders** [comment]
Wow! That was quick! Thanks @tsturm 

Fixed by https://github.com/x3dom/x3dom/commit/d3b277e4acccd36beb73d4b16cea013dd8c7eeed
