### ISSUE TITLE
x3dom download/dev issue.  Works in 1.7.1

### ISSUE THREAD

**Issue by coderextreme** [x3dom/x3dom#696]
x3dom-full.js:3983 Uncaught TypeError: newView.mult is not a function
    at x3dom.registerNodeType.defineClass.fieldChanged.setView (x3dom-full.js:3983)
    at x3dom.TurntableNavigation.animateTo (x3dom-full.js:4205)
    at x3dom.Viewarea.animateTo (x3dom-full.js:1356)
    at x3dom.registerNodeType.defineClass.fieldChanged.activate (x3dom-full.js:3982)
    at x3dom.BindableStack.replaceTop (x3dom-full.js:3093)
    at x3dom.BindableBag.addBindable (x3dom-full.js:3109)
    at x3dom.registerNodeType.defineClass.fieldChanged.nodeChanged (x3dom-full.js:2938)
    at x3dom.NodeNameSpace.setupTree (x3dom-full.js:2856)
    at x3dom-full.js:2856
    at Function.Array.forEach (x3dom-full.js:2)
x3dom-full.js:3983 Uncaught TypeError: newView.mult is not a function
    at x3dom.registerNodeType.defineClass.fieldChanged.setView (x3dom-full.js:3983)
    at x3dom.TurntableNavigation.animateTo (x3dom-full.js:4205)
    at x3dom.Viewarea.animateTo (x3dom-full.js:1356)
    at x3dom.registerNodeType.defineClass.fieldChanged.activate (x3dom-full.js:3982)
    at x3dom.BindableStack.push (x3dom-full.js:3092)
    at x3dom.registerNodeType.defineClass.fieldChanged.bind (x3dom-full.js:2934)
    at x3dom.registerNodeType.defineClass.fieldChanged.fieldChanged (x3dom-full.js:3987)
    at x3dom.registerNodeType.defineClass.fieldChanged.updateField (x3dom-full.js:2888)
    at HTMLUnknownElement.x3dom.setElementAttribute [as setAttribute] (x3dom-full.js:2818)
    at Osm2X3dGround.updateView (earth.js:132)

**Comment by coderextreme** [comment]
Line 132 is:  self.viewpoint.setAttribute('set_bind', 'true');

**Comment by coderextreme** [comment]
I believe this has to do with the turntable navType.  Thanks!

**Comment by mlimper** [comment]
@skluge could you have a look at some point (not necessarily during the holidays, of course ;- )

**Comment by jamesleesaunders** [comment]
Can this be closed? 
Is this still an issue with v1.8.0 ?

**Comment by coderextreme** [comment]
I'd have to search for some code which uses turntable.  I don't have any turntable code that I know of.

I think code in question starts here:

Osm2X3dGround.updateView (earth.js:132)

I suggest looking for clement igonet's code.  I will look around.

John
